EXTRA_CFLAGS += \
	-I$(rtai_dir)/include \
	-I$(top_srcdir)/include \
	-I$(top_builddir)/include \
	-I$(srcdir) \
	$(rtfirewire_extradef) \
	-D__IN_RTFW__

obj-m += $(build_target).o

rt_ieee1394-objs := $(build_objs)

